### ISSUE TITLE
duplicate entities which can't be removed

### ISSUE THREAD

**Issue by martinhoess** [fredck/lightener#13]
Somehow, since the last update I have duplicate entities which cant be removed

![image](https://github.com/fredck/lightener/assets/47973549/37b178b4-c15b-4d17-b5c3-b9e87b47209a)

Funny thing they are not in any of the .storage files

**Comment by fredck** [comment]
That's an issue related to the newly introduced UI based configuration and there is no workaround for it, I'm sorry.

### Breaking changes with Lightener v2

Configuring Lightener lights in configuration.yaml is still possible but it is not anymore the best way for it. The proper way to do so now is through the UI in the Integrations page. Just click in "Add integration" and search for "Lightener".

### Solution

Lighteners from configuration.yaml now don't have a unique_id and therefore HA created a new entity for them. The old lights (the ones not ending with "_2") should be "deletable" and (maybe) HA will create them again after restarting (I didn't try this, so let us know!)

The ideal solution instead is starting from scratch, which means deleting all the entries from configuration.yaml and recreating them thought the UI in the Integrations page. You'll be able to assign them the same entity_id you had before so any existing automation will continue to work.

Let us know if this works for you. Thanks!

**Comment by fredck** [comment]
I've amended the release description, pointing to this issue as a reference for migration problems.

Apart from the issue described here, there should be no other problems and Lightener should work just like before, just with a much nicer way to configure it (and several minor fixes and improvements as well).

This is probably be the only big breaking release of Lightener but it was necessary so we could bring it to its next level in terms of seemingless integration with HA. Again, I'm sorry for the troubles during the migration.

**Comment by martinhoess** [comment]
After I removed the integration and added it again, the duplicates are gone. 👍 

(For a system where you play around a lot I like YAML more, but for "the general public" config via the interface is probably the nicer way)

**Comment by fredck** [comment]
@martinhoess, thanks for letting us know. In fact, removing and re-installing the integration is even a better option.

> (For a system where you play around a lot I like YAML more, but for "the general public" config via the interface is probably the nicer way)

The biggest advantage with the UI options is that there is no need to restart HA when creating or changing configurations. But yes, YAML rules and fits the bill as well ;)
