### ISSUE TITLE
Control covers?

### ISSUE THREAD

**Issue by itpeters** [fredck/lightener#133]
Hi @fredck ,

I have four smart blinds in my basement that all share a top position, but one of the four is shorter than the other three. (It sounds a little odd but actually makes sense in the room.)

I found myself wishing I could control them more naturally as a group. I currently have them grouped in HA, but when setting them to a position other than fully open or fully closed, it's a little unfortunate that they don't visually line up. As a current lightener user, I immediately wondered whether lightener could create a cover group that allowed me more sophisticated control of the cover ranges (so that the oddball shade would line up with the others at arbitrary percentages).

I see that you mentioned this in #26 as originally part of the scope of the integration but eventually set aside. I was curious if your thinking remains the same there? Assuming you want lightener to remain light-specific, do you have any thoughts on what would be involved in hacking up a version that works for shades, before I dive into it?

Thanks!

**Comment by fredck** [comment]
Yes, my comment in https://github.com/fredck/lightener/issues/26#issuecomment-1583603259 is conclusive. There is no plans for that as it involves a lot of tests, issues and new use cases (e.g. covers don't have on/off state) that are out of the scope of the integration.

But you can hack it in a different way, by using ha features.

You could create helper "lights" using the the [Template Light](https://www.home-assistant.io/integrations/light.template/) integration that would sync the lights brightness to the curtains position.

Then, the other way around. You create a helper "cover" using the [Template Cover](https://www.home-assistant.io/integrations/cover.template/) integration that syncs with the Lightener entry that controls the above "lights".

All this would work behind the scenes, transparent to the end user.

So well... you wanted to hack this up... here you have it :)
