### ISSUE TITLE
Question: Is it possible to edit the values via a text file?

### ISSUE THREAD

**Issue by jamespaulley** [fredck/lightener#137]
Hi, sorry if this is the wrong place for this. This software is brilliant! But is it possible to edit the values via a text file or something, so I don't have to keep clicking through all the lights every time I want to make a change? Cheers

**Comment by fredck** [comment]
Well, that's a common thing with all integrations so it doesn't make sense for this being an integration feature.

Maybe HA will make this easier in the future but configurations can be manually modified. Check out one of the discussions that Google gave me: https://www.reddit.com/r/homeassistant/comments/jcajrh/is_it_possible_to_reconfigure_integrations_set_up/

Just ofc, be cautions when touching files in the `.storage` directory.
