### ISSUE TITLE
Brightness is off by 1 percent on a defined setting

### ISSUE THREAD

**Issue by Patrick1610** [fredck/lightener#37]
I have a setting that defines 30:50 (and 30:75 for the other light). As seen in the image when the brightness is set to 30%, the percentages of the lights are 49% and 74%. 
While that is understandable with calculated values, I think this shouldn't happen at defined settings. 

Is this happening to others?

![image](https://github.com/fredck/lightener/assets/6585375/ee221fac-803d-4d69-8fce-76d1d80e3af2)

**Comment by fredck** [comment]
Other than the above, the recent release of Lightener v2.3.0 ads more precision to the mapping. We should be fine here.
