### ISSUE TITLE
Wrong brightness when turning on

### ISSUE THREAD

**Issue by daniel1v** [fredck/lightener#41]
Hi,

I am experiencing unexpected behavior, when turning on my lightener lights:

My lightener group consists of two dimmable lights. The first one has a default mapping. The second one should turn on when the virtual light is at 50%.

Everything is working as expected, when I use the brightness slider of my virtual light. But when I only toggle it on, without setting a brightness value, I get unexpected behavior. 

Lets say, the last brightness of my virtual light was 30%, before I turned it off. Light 1 was also 30% , light 2 was off. When I switch the virtual light back on, it recovers its last brightness value (30%). The light with default mapping is then turned on correctly with 30%. And here the unexpected thing: light 2 is also turned on, even though it should stay off.

Edit:
Mapping for light 2:
50:0
100:100

**Comment by bobzer** [comment]
Yep I got the exact same problem

**Comment by daniel1v** [comment]
@fredck ping
