### ISSUE TITLE
Add integration error

### ISSUE THREAD

**Issue by j1104c** [fredck/lightener#50]
I added and integrated it to show  User input malformed: extra keys not allowed @ data['filter']  How can I improve it?
Thanks

**Comment by MichDem** [comment]
I have that problem as well. When I try to add a new Integration, regardless of the name it's giving me the same error as above

**Comment by fredck** [comment]
I couldn't reproduce the issue. Can you provide us more precise steps?

**Comment by MichDem** [comment]
It works now, I'm not sure what update caused it to work once again, but I'm able to create light groups now without any errors

**Comment by fredck** [comment]
@MichDem, thank you for the confirmation.
