### ISSUE TITLE
No config flow

### ISSUE THREAD

**Issue by genebean** [fredck/lightener#9]
The docs say I should get a configuration flow but I get this instead 

![IMG_2111](https://github.com/fredck/lightener/assets/966789/c2bfe047-00a8-4eb3-b871-b57e63a8ee80)

**Comment by fredck** [comment]
I've mistakenly thought that HACS shows the README file from the current released but instead it shows the one in the master branch. Yesterday #8 landed on master, introducing config flows and a new README but this will be available just after we release Lightener v2.

I've reverted the README change with 785bf48 and I'll reintroduce it once v2 is released.

**Comment by genebean** [comment]
Thanks for the quick response
